### PR TITLE
Repeatable fields prototype

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Based on work done in #49 by @wesm87
## Tasks
- [ ] Make Add New button text be customizable
- [ ] Review JS with a core contributor
- [ ] Don't use JS DOM manipulation, utilize Backbone better and re-render
- [ ] Add Sortable integration
- [ ] Store repeatable control info on the current page, in an array and localize it to JS
- [ ] Look into what CSS we might need for styling the remove buttons in a way that looks better, maybe we can leverage some core WP CSS classes?

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
@wesm87 i've got things saving now, pretty basic, no nice styles, but I know for a fact the JS side of this needs love since getting the JS part of this into core needs to be done in such a way that follows how core handles Backbone JS and structures currently, I have a feeling this might just be slightly different. Maybe we can rope in someone like @adamsilverstein or a core contributor who has worked with core JS before to consult us on what we need to do.

**Comment by sc0ttkclark** [comment]
Just a quick note -- I updated the JS file itself, I didn't update the .coffee script yet, and it's not been formatted for WP JS coding standards yet.

**Comment by sc0ttkclark** [comment]
Added a couple of tasks to the main PR description to keep track of ongoing things.

Related issue: #8

**Comment by sc0ttkclark** [comment]
@ryanwelcher would love your help here on the JS side of this, as well as localizing the control information on output like input name etc.

Also sorting :)

**Comment by szepeviktor** [comment]
@sc0ttkclark Is this like a dream-come-true? 😌

**Comment by sc0ttkclark** [comment]
make.wordpress.org post incoming shortly :) We rebooted the project and had a kick-off meeting last week 🎉

**Comment by mihdan** [comment]
This is the best New Year's present for a developer 🦄

**Comment by sc0ttkclark** [comment]
The post is published here: https://make.wordpress.org/core/2023/01/09/fields-api-kick-off-chat-summary-january-5th-2023/

**Pull request closed without merging**
