### PR TITLE
initial attempt at nav_menu_item implementation

### PR DESCRIPTION
**Pull request by lucyllewy**
This doesn't touch the wp-customize code! I also have no idea whether it actually works :-p ref: #34

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Oh wow, you put this together pretty quickly! Any notes you'd like to give me on your experience with working with the Fields API as you were building this? Any things that could be better for you or confusion with naming of things?

**Comment by diddledan** [comment]
the only thing that comes to mind as something that might be able to be improved is that I had to write a save routine which was almost a complete carbon-copy of the same function from the user profile class. I think if it's likely to be the same for every other implementation then it might be better to abstract that so that saving is handled by a central function which is wired-up automatically when the fields are displayed. This function would need to either be replaceable per screen or have ample hooks in-place to customise its behaviour, but I do think there's mileage in moving it out of each implementation's remit by default.

**Comment by sc0ttkclark** [comment]
Related: #34

**Comment by sc0ttkclark** [comment]
Going to close this one due to the problems with including it in WP core (too many fields on a page), we can open a new PR for this if a solution gets figured out.

Otherwise, I'd say let's focus only on the Customizer Menu editor side of this.

**Comment by sc0ttkclark** [comment]
Looks like they solved it in core https://core.trac.wordpress.org/changeset/36510

**Comment by sc0ttkclark** [comment]
Closing in favor of #68

**Pull request closed without merging**
